version: '3.8'

services:
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8000"
    environment:
      - MODEL_NAME=cardiffnlp/twitter-xlm-roberta-base-sentiment
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "5000:80"
    environment:
      - AI_URL=http://ai-service:8000
      - ConnectionStrings__ChatDb=Data Source=/app/data/chat.db
    volumes:
      - backend_data:/app/data
    depends_on:
      - ai-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/swagger"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
